### ISSUE TITLE
Ordered item options aren't rendered as expected on PDF

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2-jp#109]
# Preconditions

1. Install Magento2.3.4 with sample data.
2. Install ConfigurablePdfFont and Font modules.
3. Set Japanese as store language.
4. Set PDF font to "Source Hans Sans Japanese".
5. Change product attribute label of "Color" to "カラー"
6. Create order.
7. Create invoice.
8. Print pdf.

# Expected result
<img width="588" alt="correct-pdf-result" src="https://user-images.githubusercontent.com/124136/73411140-a77dcd00-4347-11ea-8dae-9ccae139f1cb.png">

# Actual result
<img width="594" alt="wrong-pdf-result" src="https://user-images.githubusercontent.com/124136/73411146-ad73ae00-4347-11ea-84af-c16a5a8ff28b.png">

**Comment by lenaorobei** [comment]
Fixed in https://github.com/magento/magento2-jp/pull/110
