### ISSUE TITLE
add csp_whitelist.xml for postalcode

### ISSUE THREAD

**Issue by HirokazuNishi** [magento/magento2-jp#112]
SInce Magento2.3.5, CSP was added as default feature. All external assets have to define in csp_whitelist.xml. Otherwise non-whitelisted assets loading or XHR are intercepted by browsers.

JapanesePostalCode already uses madefor.github.io api for converting address from zipcode. It should be whitelisted.

**Comment by lenaorobei** [comment]
Fixed https://github.com/magento/magento2-jp/pull/113
