### ISSUE TITLE
Create MagentoJapan Composer meta-package

### ISSUE THREAD

**Issue by vkublytskyi** [magento/magento2-jp#30]
Create Composer meta-package to be able install all Japanese localization modules by single Composer require command.

**Comment by piotrekkaminski** [comment]
@vkublytskyi any idea on naming? It should be universal pattern for other languages - can it be something like magento-localization-japan ?

**Comment by vkublytskyi** [comment]
`magento-localization-japan` sounds good. As alternative we may use simple `magento-japan` name as PHP code uses `MagentoJapan` as root namespace. But I don't have any strong opinion on this.

**Comment by vkublytskyi** [comment]
So far created meta package at repository root. However, this approach is not verified and probably we will convert it to a separate module (like Magento_B2B).

**Comment by vkublytskyi** [comment]
For simplicity of automatic packaging meta package moved from root folder into `_metapackage`
