### ISSUE TITLE
Remove all Coding Standards Ignore annotations

### ISSUE THREAD

**Issue by ishakhsuvarov** [magento/magento2-jp#56]
Some files contain `@codingStandardsIgnoreFile` annotation, which stops static tests from being effective.

Annotation should be removed and files refactored to comply with the existing coding standards.

**Comment by vkublytskyi** [comment]
`@codingStandardsIgnoreFile` now used only templates that are copied from Magento core modules and should include only code required to make additional fields fork. Other changes to templates will complicate maintenance up-to-date code of these templates.
