### ISSUE TITLE
Magento\JapaneseAddress\Plugin\Customer\Model\Name doesn't exist

### ISSUE THREAD

**Issue by akycop** [magento/magento2-jp#81]
Hi, there,
I have been enabled these modules.
- Magento_CurrencyPrecision
- Magento_JapaneseAddress                                                                                 
- Magento_JapaneseDefaultConfig                                                                           │
- Magento_JapaneseDefaultCmsPages                                                                         │
- Magento_JapaneseName                                                                                    │
- Magento_JapanesePostalCode                                                                              │
- Magento_JapaneseRegion                                                                                  │
- Magento_JapaneseStoreAddress                                                                            │
- Magento_JapaneseYenFormatting

After enabled modules, It show below log.
`
Plugin class Magento\JapaneseAddress\Plugin\Customer\Model\Name doesn't exist
main.CRITICAL: Plugin class Magento\CurrencyPrecision\Plugin\Directory\Model\CurrencyPrecisionFormatting doesn't exist [] []
main.CRITICAL: Plugin class Magento\JapaneseName\Plugin\Framework\Data\ExtensionAttributesValues doesn't exist [] []
Plugin class Magento\CurrencyPrecision\Plugin\Directory\Model\CurrencyPrecisionFormatting doesn't exist
`

Environment
・magento 2.3.0(update from 2.2.7 by composer)
・php7.2 + nginx + varnish

Please tell me what should I do.
Thank you

**Comment by vkublytskyi** [comment]
Hi, @akycop. Thank you for your interest in the project.

Source code of the plugin is located at https://github.com/magento/magento2-jp/blob/2.3-develop/JapaneseAddress/Plugin/Customer/Model/Name.php. As during work on the project we several times changes the structure of folders and vendor name installation guide was a little outdated. Today I updated guide on how to add Japanese modules to Git-based Magento installation. You may find it at https://github.com/magento/magento2-jp/blob/2.3-develop/README.md#installation-from-git. It should solve an issue with classes autoloading.

Please let me know if the proposed installation guide works for you or issue still exists and we should find another one solution.

**Comment by vkublytskyi** [comment]
@akycop I'm closing issue as seems it is related to local installation issues. Please reopen this issue or create new if you will discover steps to reproduce.
