### ISSUE TITLE
Checkout shipping address form Kana ordering

### ISSUE THREAD

**Issue by ghost** [magento/magento2-jp#82]
Hello,

Just installed yesterday. Working very charm. Really wonderful experience.

I'm not sure this is temporary issue or not, the order of Kana form on checkout page, **Family name's furigana** and **First name's furigana**, they are now reverse. I think, at least, the current ordering is not so natural.
Please kindly see the below images.

![shipping-address](https://user-images.githubusercontent.com/48812909/54861624-49677d00-4d67-11e9-8d5f-4a7600a7bd26.jpg)

![shipping-address2](https://user-images.githubusercontent.com/48812909/54873273-0f04eb00-4e0e-11e9-9246-71f6a030001b.jpg)

How to change the ordering of the shipping address kana form on checkout page?

Best,

**Comment by HirokazuNishi** [comment]
@Magedeki The issue was fixed and merged into 2.3-develop branch. Please test from Magento2.3 installation. Unfortunately, Magento2 renders checkout form fields by customer_eav_attribute.sort_order value. It can only have single value for each attributes against all store views. So if you hope to optimize checkout form fields position against multi languages, you need to customize by yourself.

**Comment by ghost** [comment]
@HirokazuNishi Thank you very much for your reply. Noted about the checkout form's attribute sort_order.

Sorry, now get the below error while running `bin/magento setup:upgrade`

_Warning: call_user_func() expects parameter 1 to be a valid callback, class 'CommunityEngineering\JapaneseName\Setup\Patch\Data\KanaAttributes' not found in /magento2-root-path/lib/internal/Magento/Framework/Setup/Patch/PatchRegistry.php on line 139_

Any suggestions will be really appreciated.

**Comment by HirokazuNishi** [comment]
@Magedeki magento2-jp modules were renamed from Magento to CommunityEngineering namespace. Please check your local directory structure under app/code.

**Comment by ghost** [comment]
@HirokazuNishi Yes, I confirmed the Kana form ordering issue was fixed. Thanks for your advice!

**Comment by vkublytskyi** [comment]
Closed as fix is confirmed
