### ISSUE TITLE
Catalog price with comma is stored incorrectly

### ISSUE THREAD

**Issue by ghost** [magento/magento2-jp#86]
Hello,

Catalog price with comma is rounded to 1 digit number as the comma " , " is converted to the decimal point " . " automatically. 

example:
3,700 > 3.700 > 4

![catalog-price](https://user-images.githubusercontent.com/48812909/55129099-d5efb200-5150-11e9-893e-9e95fdf75d8d.jpg)

If the price is saved without comma, the correct price is stored with comma, though.

example
3700 > 3,700

Any suggestions will be really appreciated.

Best,

**Comment by HirokazuNishi** [comment]
@vkublytskyi This issue is related with Magento\Framework\Locale\Format.php .
getNumber method doesn't consider comma only integer data pattern.
